::DEF.C.Weapons <- {
    //==================================================================================================
    //Dagger 
    //==================================================================================================
    
        // 1H 
        "weapon.knife" : {
            "RegularDamage" : 1,
            "RegularDamageMax" : 2,
            "ArmorDamageMult" : 0.5,
            "DirectDamageMult" : 0.2,
        },
        "weapon.dagger" : {
            "RegularDamage" : 1,
            "RegularDamageMax" : 3,
            "ArmorDamageMult" : 0.6,
            "DirectDamageMult" : 0.2,
        },
        "weapon.named_dagger" : {
            "RegularDamage" : 2,
            "RegularDamageMax" : 4,
            "ArmorDamageMult" : 0.7,
            "DirectDamageMult" : 0.2,
        },
        "weapon.rondel_dagger" : {
            "RegularDamage" : 2,
            "RegularDamageMax" : 4,
            "ArmorDamageMult" : 0.7,
            "DirectDamageMult" : 0.2,
        },
        "weapon.named_qatal_dagger" : {
            "RegularDamage" : 3,
            "RegularDamageMax" : 4,
            "ArmorDamageMult" : 0.7,
            "DirectDamageMult" : 0.2,
        },
        "weapon.obsidian_dagger" : {
            "RegularDamage" : 2,
            "RegularDamageMax" : 4,
            "ArmorDamageMult" : 0.7,
            "DirectDamageMult" : 0.2,
        },
        "weapon.qatal_dagger" : {
            "RegularDamage" : 3,
            "RegularDamageMax" : 4,
            "ArmorDamageMult" : 0.7,
            "DirectDamageMult" : 0.2,
        },
        // 2H 
    
    
    
    //==================================================================================================
    //Sword 
    //==================================================================================================
    
        // 1H 
        "weapon.goblin_notched_blade" : {
            "StaminaModifier" : -1,
            "RegularDamage" : 2,
            "RegularDamageMax" : 3,
            "ArmorDamageMult" : 0.6,
            "DirectDamageMult" : 0.2,
        },
        "weapon.broken_ancient_sword" : {
            "StaminaModifier" : -1,
            "RegularDamage" : 3,
            "RegularDamageMax" : 3,
            "ArmorDamageMult" : 0.75,
            "DirectDamageMult" : 0.2,
        },
        "weapon.saif" : {
            "StaminaModifier" : -1,
            "RegularDamage" : 3,
            "RegularDamageMax" : 4,
            "ArmorDamageMult" : 0.65,
            "DirectDamageMult" : 0.2,
        },
        "weapon.shortsword" : {
            "StaminaModifier" : -1,
            "RegularDamage" : 3,
            "RegularDamageMax" : 4,
            "ArmorDamageMult" : 0.75,
            "DirectDamageMult" : 0.2,
        },
        "weapon.ancient_sword" : {
            "StaminaModifier" : -1,
            "RegularDamage" : 3,
            "RegularDamageMax" : 4,
            "ArmorDamageMult" : 0.8,
            "DirectDamageMult" : 0.2,
        },
        "weapon.arming_sword" : {
            "StaminaModifier" : -1,
            "RegularDamage" : 4,
            "RegularDamageMax" : 4,
            "ArmorDamageMult" : 0.8,
            "DirectDamageMult" : 0.2,
        },
        "weapon.falchion" : {
            "StaminaModifier" : -1,
            "RegularDamage" : 3,
            "RegularDamageMax" : 4,
            "ArmorDamageMult" : 0.7,
            "DirectDamageMult" : 0.2,
        },
        "weapon.goblin_falchion" : {
            "StaminaModifier" : -1,
            "RegularDamage" : 3,
            "RegularDamageMax" : 4,
            "ArmorDamageMult" : 0.7,
            "DirectDamageMult" : 0.2,
        },
        "weapon.named_goblin_falchion" : {
            "StaminaModifier" : -1,
            "RegularDamage" : 3,
            "RegularDamageMax" : 4,
            "ArmorDamageMult" : 0.7,
            "DirectDamageMult" : 0.2,
        },
        "weapon.scimitar" : {
            "StaminaModifier" : -1,
            "RegularDamage" : 4,
            "RegularDamageMax" : 4,
            "ArmorDamageMult" : 0.7,
            "DirectDamageMult" : 0.2,
        },
        "weapon.fencing_sword" : {
            "StaminaModifier" : -1,
            "RegularDamage" : 3,
            "RegularDamageMax" : 5,
            "ArmorDamageMult" : 0.75,
            "DirectDamageMult" : 0.2,
        },
        "weapon.named_fencing_sword" : {
            "StaminaModifier" : -1,
            "RegularDamage" : 3,
            "RegularDamageMax" : 5,
            "ArmorDamageMult" : 0.75,
            "DirectDamageMult" : 0.2,
        },
        "weapon.named_shamshir" : {
            "StaminaModifier" : -1,
            "RegularDamage" : 4,
            "RegularDamageMax" : 5,
            "ArmorDamageMult" : 0.75,
            "DirectDamageMult" : 0.2,
        },
        "weapon.named_sword" : {
            "StaminaModifier" : -1,
            "RegularDamage" : 4,
            "RegularDamageMax" : 5,
            "ArmorDamageMult" : 0.85,
            "DirectDamageMult" : 0.2,
        },
        "weapon.noble_sword" : {
            "StaminaModifier" : -1,
            "RegularDamage" : 4,
            "RegularDamageMax" : 5,
            "ArmorDamageMult" : 0.85,
            "DirectDamageMult" : 0.2,
        },
        "weapon.shamshir" : {
            "StaminaModifier" : -1,
            "RegularDamage" : 4,
            "RegularDamageMax" : 5,
            "ArmorDamageMult" : 0.75,
            "DirectDamageMult" : 0.2,
        },
        "weapon.lightbringer_sword" : {
            "StaminaModifier" : -1,
            "RegularDamage" : 5,
            "RegularDamageMax" : 5,
            "ArmorDamageMult" : 0.9,
            "DirectDamageMult" : 0.2,
        },
        // 2H 
        "weapon.rhomphaia" : {
            "StaminaModifier" : -2,
            "RegularDamage" : 4,
            "RegularDamageMax" : 6,
            "ArmorDamageMult" : 1.05,
            "DirectDamageMult" : 0.2,
            "ChanceToHitHead" : 5,
        },
        "weapon.named_warbrand" : {
            "StaminaModifier" : -2,
            "RegularDamage" : 5,
            "RegularDamageMax" : 7,
            "ArmorDamageMult" : 0.75,
            "DirectDamageMult" : 0.2,
            "ChanceToHitHead" : 5,
        },
        "weapon.warbrand" : {
            "StaminaModifier" : -2,
            "RegularDamage" : 5,
            "RegularDamageMax" : 7,
            "ArmorDamageMult" : 0.75,
            "DirectDamageMult" : 0.2,
            "ChanceToHitHead" : 5,
        },
        "weapon.longsword" : {
            "StaminaModifier" : -2,
            "RegularDamage" : 6,
            "RegularDamageMax" : 8,
            "ArmorDamageMult" : 1.0,
            "DirectDamageMult" : 0.25,
            "ChanceToHitHead" : 5,
        },
        "weapon.greatsword" : {
            "StaminaModifier" : -2,
            "RegularDamage" : 8,
            "RegularDamageMax" : 10,
            "ArmorDamageMult" : 1.0,
            "DirectDamageMult" : 0.25,
            "ChanceToHitHead" : 5,
        },
        "weapon.named_greatsword" : {
            "StaminaModifier" : -2,
            "RegularDamage" : 8,
            "RegularDamageMax" : 10,
            "ArmorDamageMult" : 1.0,
            "DirectDamageMult" : 0.25,
            "ChanceToHitHead" : 5,
        },
    
    
    
    //==================================================================================================
    //Cleaver 
    //==================================================================================================
    
        // 1H 
        "weapon.thorned_whip" : {
            "RangeMin" : 1,
            "RangeMax" : 3,
            "RangeIdeal" : 3,
            "StaminaModifier" : -1,
            "RegularDamage" : 1,
            "RegularDamageMax" : 2,
            "ArmorDamageMult" : 0.3,
            "DirectDamageMult" : 0.1,
        },
        "weapon.antler_cleaver" : {
            "StaminaModifier" : -1,
            "RegularDamage" : 2,
            "RegularDamageMax" : 3,
            "ArmorDamageMult" : 0.75,
            "DirectDamageMult" : 0.25,
        },
        "weapon.battle_whip" : {
            "RangeMin" : 1,
            "RangeMax" : 3,
            "RangeIdeal" : 3,
            "StaminaModifier" : -1,
            "RegularDamage" : 1,
            "RegularDamageMax" : 3,
            "ArmorDamageMult" : 0.25,
            "DirectDamageMult" : 0.1,
        },
        "weapon.named_battle_whip" : {
            "RangeMin" : 1,
            "RangeMax" : 3,
            "RangeIdeal" : 3,
            "StaminaModifier" : -1,
            "RegularDamage" : 1,
            "RegularDamageMax" : 3,
            "ArmorDamageMult" : 0.25,
            "DirectDamageMult" : 0.1,
        },
        "weapon.butchers_cleaver" : {
            "StaminaModifier" : -1,
            "RegularDamage" : 2,
            "RegularDamageMax" : 3,
            "ArmorDamageMult" : 0.75,
            "DirectDamageMult" : 0.25,
        },
        "weapon.falx" : {
            "StaminaModifier" : -1,
            "RegularDamage" : 2,
            "RegularDamageMax" : 3,
            "ArmorDamageMult" : 0.8,
            "DirectDamageMult" : 0.25,
        },
        "weapon.blunt_cleaver" : {
            "StaminaModifier" : -1,
            "RegularDamage" : 3,
            "RegularDamageMax" : 4,
            "ArmorDamageMult" : 0.8,
            "DirectDamageMult" : 0.25,
        },
        "weapon.scramasax" : {
            "StaminaModifier" : -1,
            "RegularDamage" : 3,
            "RegularDamageMax" : 4,
            "ArmorDamageMult" : 0.8,
            "DirectDamageMult" : 0.25,
        },
        "weapon.khopesh" : {
            "StaminaModifier" : -1,
            "RegularDamage" : 3,
            "RegularDamageMax" : 5,
            "ArmorDamageMult" : 1.2,
            "DirectDamageMult" : 0.25,
        },
        "weapon.named_khopesh" : {
            "StaminaModifier" : -1,
            "RegularDamage" : 3,
            "RegularDamageMax" : 5,
            "ArmorDamageMult" : 1.2,
            "DirectDamageMult" : 0.25,
        },
        "weapon.military_cleaver" : {
            "StaminaModifier" : -1,
            "RegularDamage" : 4,
            "RegularDamageMax" : 6,
            "ArmorDamageMult" : 0.9,
            "DirectDamageMult" : 0.25,
        },
        "weapon.named_cleaver" : {
            "StaminaModifier" : -1,
            "RegularDamage" : 4,
            "RegularDamageMax" : 6,
            "ArmorDamageMult" : 0.9,
            "DirectDamageMult" : 0.25,
        },
        "weapon.named_orc_cleaver" : {
            "StaminaModifier" : -1,
            "RegularDamage" : 4,
            "RegularDamageMax" : 7,
            "ArmorDamageMult" : 1.1,
            "DirectDamageMult" : 0.25,
        },
        "weapon.orc_cleaver" : {
            "StaminaModifier" : -1,
            "RegularDamage" : 4,
            "RegularDamageMax" : 7,
            "ArmorDamageMult" : 1.1,
            "DirectDamageMult" : 0.25,
        },
        // 2H 
        "weapon.two_handed_saif" : {
            "StaminaModifier" : -2,
            "RegularDamage" : 5,
            "RegularDamageMax" : 7,
            "ArmorDamageMult" : 0.9,
            "DirectDamageMult" : 0.25,
        },
        "weapon.crypt_cleaver" : {
            "StaminaModifier" : -2,
            "RegularDamage" : 6,
            "RegularDamageMax" : 8,
            "ArmorDamageMult" : 1.2,
            "DirectDamageMult" : 0.25,
        },
        "weapon.named_crypt_cleaver" : {
            "StaminaModifier" : -2,
            "RegularDamage" : 6,
            "RegularDamageMax" : 8,
            "ArmorDamageMult" : 1.2,
            "DirectDamageMult" : 0.25,
        },
        "weapon.named_rusty_warblade" : {
            "StaminaModifier" : -2,
            "RegularDamage" : 6,
            "RegularDamageMax" : 8,
            "ArmorDamageMult" : 1.1,
            "DirectDamageMult" : 0.25,
        },
        "weapon.rusty_warblade" : {
            "StaminaModifier" : -2,
            "RegularDamage" : 6,
            "RegularDamageMax" : 8,
            "ArmorDamageMult" : 1.1,
            "DirectDamageMult" : 0.25,
        },
        "weapon.named_two_handed_scimitar" : {
            "StaminaModifier" : -2,
            "RegularDamage" : 6,
            "RegularDamageMax" : 8,
            "ArmorDamageMult" : 1.1,
            "DirectDamageMult" : 0.25,
        },
        "weapon.two_handed_scimitar" : {
            "StaminaModifier" : -2,
            "RegularDamage" : 6,
            "RegularDamageMax" : 8,
            "ArmorDamageMult" : 1.1,
            "DirectDamageMult" : 0.25,
        },
    
    
    
    //==================================================================================================
    //Axe 
    //==================================================================================================
    
        // 1H 
        "weapon.crude_axe" : {
            "StaminaModifier" : -1,
            "RegularDamage" : 3,
            "RegularDamageMax" : 4,
            "ArmorDamageMult" : 1.2,
            "DirectDamageMult" : 0.3,
        },
        "weapon.hatchet" : {
            "StaminaModifier" : -1,
            "RegularDamage" : 2,
            "RegularDamageMax" : 4,
            "ArmorDamageMult" : 1.1,
            "DirectDamageMult" : 0.3,
        },
        "weapon.hand_axe" : {
            "StaminaModifier" : -1,
            "RegularDamage" : 3,
            "RegularDamageMax" : 4,
            "ArmorDamageMult" : 1.2,
            "DirectDamageMult" : 0.3,
        },
        "weapon.fighting_axe" : {
            "StaminaModifier" : -1,
            "RegularDamage" : 3,
            "RegularDamageMax" : 5,
            "ArmorDamageMult" : 1.3,
            "DirectDamageMult" : 0.3,
        },
        "weapon.named_axe" : {
            "StaminaModifier" : -1,
            "RegularDamage" : 3,
            "RegularDamageMax" : 5,
            "ArmorDamageMult" : 1.3,
            "DirectDamageMult" : 0.3,
        },
        "weapon.named_orc_axe" : {
            "StaminaModifier" : -1,
            "RegularDamage" : 3,
            "RegularDamageMax" : 6,
            "ArmorDamageMult" : 1.3,
            "DirectDamageMult" : 0.3,
        },
        "weapon.orc_axe" : {
            "StaminaModifier" : -1,
            "RegularDamage" : 3,
            "RegularDamageMax" : 6,
            "ArmorDamageMult" : 1.3,
            "DirectDamageMult" : 0.3,
        },
        // 2H 
        "weapon.longaxe" : {
            "StaminaModifier" : -2,
            "RangeMin" : 1,
            "RangeMax" : 2,
            "RangeIdeal" : 2,
            "RegularDamage" : 4,
            "RegularDamageMax" : 7,
            "ArmorDamageMult" : 1.1,
            "DirectDamageMult" : 0.3,
            "ChanceToHitHead" : 5,
        },
        "weapon.woodcutters_axe" : {
            "StaminaModifier" : -2,
            "RegularDamage" : 3,
            "RegularDamageMax" : 7,
            "ArmorDamageMult" : 1.25,
            "DirectDamageMult" : 0.4,
            "ChanceToHitHead" : 0,
        },
        "weapon.heavy_rusty_axe" : {
            "StaminaModifier" : -2,
            "RegularDamage" : 7,
            "RegularDamageMax" : 9,
            "ArmorDamageMult" : 1.5,
            "DirectDamageMult" : 0.4,
            "ChanceToHitHead" : 0,
        },
        "weapon.named_heavy_rusty_axe" : {
            "StaminaModifier" : -2,
            "RegularDamage" : 7,
            "RegularDamageMax" : 9,
            "ArmorDamageMult" : 1.5,
            "DirectDamageMult" : 0.4,
            "ChanceToHitHead" : 0,
        },
        "weapon.bardiche" : {
            "StaminaModifier" : -2,
            "RegularDamage" : 7,
            "RegularDamageMax" : 9,
            "ArmorDamageMult" : 1.3,
            "DirectDamageMult" : 0.4,
            "ChanceToHitHead" : 0,
        },
        "weapon.named_bardiche" : {
            "StaminaModifier" : -2,
            "RegularDamage" : 7,
            "RegularDamageMax" : 9,
            "ArmorDamageMult" : 1.3,
            "DirectDamageMult" : 0.4,
            "ChanceToHitHead" : 0,
        },
        "weapon.named_longaxe" : {
            "StaminaModifier" : -2,
            "RangeMin" : 1,
            "RangeMax" : 2,
            "RangeIdeal" : 2,
            "RegularDamage" : 7,
            "RegularDamageMax" : 9,
            "ArmorDamageMult" : 1.1,
            "DirectDamageMult" : 0.3,
            "ChanceToHitHead" : 5,
        },
        "weapon.greataxe" : {
            "StaminaModifier" : -2,
            "RegularDamage" : 8,
            "RegularDamageMax" : 10,
            "ArmorDamageMult" : 1.5,
            "DirectDamageMult" : 0.4,
            "ChanceToHitHead" : 0,
        },
        "weapon.named_greataxe" : {
            "StaminaModifier" : -2,
            "RegularDamage" : 8,
            "RegularDamageMax" : 10,
            "ArmorDamageMult" : 1.5,
            "DirectDamageMult" : 0.4,
            "ChanceToHitHead" : 0,
        },
        "weapon.orc_axe_2h" : {
            "StaminaModifier" : -2,
            "RegularDamage" : 9,
            "RegularDamageMax" : 12,
            "ArmorDamageMult" : 1.6,
            "DirectDamageMult" : 0.4,
            "ChanceToHitHead" : 0,
        },
    
    
    
    //==================================================================================================
    //Spear 
    //==================================================================================================
    
        // 1H 
        "weapon.militia_spear" : {
            "StaminaModifier" : -1,
            "RegularDamage" : 2,
            "RegularDamageMax" : 3,
            "ArmorDamageMult" : 0.9,
            "DirectDamageMult" : 0.25,
        },
        "weapon.ancient_spear" : {
            "StaminaModifier" : -1,
            "RegularDamage" : 2,
            "RegularDamageMax" : 3,
            "ArmorDamageMult" : 1.0,
            "DirectDamageMult" : 0.25,
        },
        "weapon.boar_spear" : {
            "StaminaModifier" : -1,
            "RegularDamage" : 3,
            "RegularDamageMax" : 3,
            "ArmorDamageMult" : 0.95,
            "DirectDamageMult" : 0.25,
        },
        "weapon.firelance" : {
            "RangeMin" : 1,
            "RangeMax" : 1,
            "RangeIdeal" : 1,
            "StaminaModifier" : -1,
            "RegularDamage" : 3,
            "RegularDamageMax" : 3,
            "ArmorDamageMult" : 1.1,
            "DirectDamageMult" : 0.25,
            "ChanceToHitHead" : 0,
        },
        "weapon.goblin_spear" : {
            "StaminaModifier" : -1,
            "RegularDamage" : 2,
            "RegularDamageMax" : 3,
            "ArmorDamageMult" : 0.7,
            "DirectDamageMult" : 0.25,
        },
        "weapon.named_goblin_spear" : {
            "StaminaModifier" : -1,
            "RegularDamage" : 2,
            "RegularDamageMax" : 3,
            "ArmorDamageMult" : 0.7,
            "DirectDamageMult" : 0.25,
        },
        "weapon.fighting_spear" : {
            "StaminaModifier" : -1,
            "RegularDamage" : 3,
            "RegularDamageMax" : 4,
            "ArmorDamageMult" : 1.0,
            "DirectDamageMult" : 0.25,
        },
        "weapon.named_spear" : {
            "StaminaModifier" : -1,
            "RegularDamage" : 3,
            "RegularDamageMax" : 4,
            "ArmorDamageMult" : 1.0,
            "DirectDamageMult" : 0.25,
        },
        // 2H 
        "weapon.warfork" : {
            "StaminaModifier" : -2,
            "RangeMin" : 1,
            "RangeMax" : 2,
            "RangeIdeal" : 2,
            "RegularDamage" : 4,
            "RegularDamageMax" : 6,
            "ArmorDamageMult" : 1.0,
            "DirectDamageMult" : 0.25,
            "ChanceToHitHead" : 5,
        },
        "weapon.goedendag" : {
            "StaminaModifier" : -2,
            "RegularDamage" : 4,
            "RegularDamageMax" : 7,
            "ArmorDamageMult" : 1.1,
            "DirectDamageMult" : 0.25,
            "ChanceToHitHead" : 0,
        },
        "weapon.named_spetum" : {
            "StaminaModifier" : -2,
            "RangeMin" : 1,
            "RangeMax" : 2,
            "RangeIdeal" : 2,
            "RegularDamage" : 5,
            "RegularDamageMax" : 7,
            "ArmorDamageMult" : 1.0,
            "DirectDamageMult" : 0.25,
            "ChanceToHitHead" : 5,
        },
        "weapon.spetum" : {
            "StaminaModifier" : -2,
            "RangeMin" : 1,
            "RangeMax" : 2,
            "RangeIdeal" : 2,
            "RegularDamage" : 5,
            "RegularDamageMax" : 7,
            "ArmorDamageMult" : 1.0,
            "DirectDamageMult" : 0.25,
            "ChanceToHitHead" : 5,
        },
    
    
    
    //==================================================================================================
    //Polearm 
    //==================================================================================================
    
        // 1H 
        // 2H 
        "weapon.pitchfork" : {
            "StaminaModifier" : -2,
            "RangeMin" : 1,
            "RangeMax" : 2,
            "RangeIdeal" : 2,
            "RegularDamage" : 3,
            "RegularDamageMax" : 5,
            "ArmorDamageMult" : 0.75,
            "DirectDamageMult" : 0.3,
            "ChanceToHitHead" : 5,
        },
        "weapon.broken_bladed_pike" : {
            "StaminaModifier" : -2,
            "RangeMin" : 1,
            "RangeMax" : 2,
            "RangeIdeal" : 2,
            "RegularDamage" : 3,
            "RegularDamageMax" : 5,
            "ArmorDamageMult" : 0.8,
            "DirectDamageMult" : 0.3,
            "ChanceToHitHead" : 5,
        },
        "weapon.goblin_pike" : {
            "StaminaModifier" : -2,
            "RangeMin" : 1,
            "RangeMax" : 2,
            "RangeIdeal" : 2,
            "RegularDamage" : 5,
            "RegularDamageMax" : 7,
            "ArmorDamageMult" : 0.9,
            "DirectDamageMult" : 0.25,
            "ChanceToHitHead" : 5,
        },
        "weapon.hooked_blade" : {
            "StaminaModifier" : -2,
            "RangeMin" : 1,
            "RangeMax" : 2,
            "RangeIdeal" : 2,
            "RegularDamage" : 4,
            "RegularDamageMax" : 7,
            "ArmorDamageMult" : 1.1,
            "DirectDamageMult" : 0.3,
            "ChanceToHitHead" : 5,
        },
        "weapon.named_goblin_pike" : {
            "StaminaModifier" : -2,
            "RangeMin" : 1,
            "RangeMax" : 2,
            "RangeIdeal" : 2,
            "RegularDamage" : 5,
            "RegularDamageMax" : 7,
            "ArmorDamageMult" : 0.9,
            "DirectDamageMult" : 0.25,
            "ChanceToHitHead" : 5,
        },
        "weapon.bladed_pike" : {
            "StaminaModifier" : -2,
            "RangeMin" : 1,
            "RangeMax" : 2,
            "RangeIdeal" : 2,
            "RegularDamage" : 5,
            "RegularDamageMax" : 8,
            "ArmorDamageMult" : 1.25,
            "DirectDamageMult" : 0.3,
            "ChanceToHitHead" : 5,
        },
        "weapon.named_bladed_pike" : {
            "StaminaModifier" : -2,
            "RangeMin" : 1,
            "RangeMax" : 2,
            "RangeIdeal" : 2,
            "RegularDamage" : 5,
            "RegularDamageMax" : 8,
            "ArmorDamageMult" : 1.25,
            "DirectDamageMult" : 0.3,
            "ChanceToHitHead" : 5,
        },
        "weapon.named_pike" : {
            "StaminaModifier" : -2,
            "RangeMin" : 1,
            "RangeMax" : 2,
            "RangeIdeal" : 2,
            "RegularDamage" : 6,
            "RegularDamageMax" : 8,
            "ArmorDamageMult" : 1.0,
            "DirectDamageMult" : 0.3,
            "ChanceToHitHead" : 5,
        },
        "weapon.named_swordlance" : {
            "StaminaModifier" : -2,
            "RangeMin" : 1,
            "RangeMax" : 2,
            "RangeIdeal" : 2,
            "RegularDamage" : 6,
            "RegularDamageMax" : 8,
            "ArmorDamageMult" : 0.9,
            "DirectDamageMult" : 0.3,
        },
        "weapon.named_warscythe" : {
            "StaminaModifier" : -2,
            "RangeMin" : 1,
            "RangeMax" : 2,
            "RangeIdeal" : 2,
            "RegularDamage" : 5,
            "RegularDamageMax" : 8,
            "ArmorDamageMult" : 1.05,
            "DirectDamageMult" : 0.3,
        },
        "weapon.pike" : {
            "StaminaModifier" : -2,
            "RangeMin" : 1,
            "RangeMax" : 2,
            "RangeIdeal" : 2,
            "RegularDamage" : 6,
            "RegularDamageMax" : 8,
            "ArmorDamageMult" : 1.0,
            "DirectDamageMult" : 0.3,
            "ChanceToHitHead" : 5,
        },
        "weapon.swordlance" : {
            "StaminaModifier" : -2,
            "RangeMin" : 1,
            "RangeMax" : 2,
            "RangeIdeal" : 2,
            "RegularDamage" : 6,
            "RegularDamageMax" : 8,
            "ArmorDamageMult" : 0.9,
            "DirectDamageMult" : 0.3,
        },
        "weapon.warscythe" : {
            "StaminaModifier" : -2,
            "RangeMin" : 1,
            "RangeMax" : 2,
            "RangeIdeal" : 2,
            "RegularDamage" : 5,
            "RegularDamageMax" : 8,
            "ArmorDamageMult" : 1.05,
            "DirectDamageMult" : 0.3,
        },
        "weapon.billhook" : {
            "StaminaModifier" : -2,
            "RangeMin" : 1,
            "RangeMax" : 2,
            "RangeIdeal" : 2,
            "RegularDamage" : 5,
            "RegularDamageMax" : 8,
            "ArmorDamageMult" : 1.4,
            "DirectDamageMult" : 0.3,
            "ChanceToHitHead" : 5,
        },
        "weapon.named_billhook" : {
            "StaminaModifier" : -2,
            "RangeMin" : 1,
            "RangeMax" : 2,
            "RangeIdeal" : 2,
            "RegularDamage" : 5,
            "RegularDamageMax" : 8,
            "ArmorDamageMult" : 1.4,
            "DirectDamageMult" : 0.3,
            "ChanceToHitHead" : 5,
        },
    
    
    
    //==================================================================================================
    //Mace 
    //==================================================================================================
    
        // 1H 
        "weapon.wooden_stick" : {
            "StaminaModifier" : -1,
            "RegularDamage" : 1,
            "RegularDamageMax" : 2,
            "ArmorDamageMult" : 0.5,
            "DirectDamageMult" : 0.4,
        },
        "weapon.claw_club" : {
            "StaminaModifier" : -1,
            "RegularDamage" : 2,
            "RegularDamageMax" : 3,
            "ArmorDamageMult" : 0.75,
            "DirectDamageMult" : 0.4,
        },
        "weapon.bludgeon" : {
            "StaminaModifier" : -1,
            "RegularDamage" : 2,
            "RegularDamageMax" : 3,
            "ArmorDamageMult" : 0.75,
            "DirectDamageMult" : 0.4,
        },
        "weapon.goblin_staff" : {
            "StaminaModifier" : -1,
            "RegularDamage" : 2,
            "RegularDamageMax" : 3,
            "ArmorDamageMult" : 0.7,
            "DirectDamageMult" : 0.4,
        },
        "weapon.nomad_mace" : {
            "StaminaModifier" : -1,
            "RegularDamage" : 2,
            "RegularDamageMax" : 3,
            "ArmorDamageMult" : 0.9,
            "DirectDamageMult" : 0.4,
        },
        "weapon.light_southern_mace" : {
            "StaminaModifier" : -1,
            "RegularDamage" : 3,
            "RegularDamageMax" : 4,
            "ArmorDamageMult" : 1.1,
            "DirectDamageMult" : 0.4,
        },
        "weapon.orc_wooden_club" : {
            "StaminaModifier" : -1,
            "RegularDamage" : 2,
            "RegularDamageMax" : 4,
            "ArmorDamageMult" : 0.75,
            "DirectDamageMult" : 0.4,
        },
        "weapon.morning_star" : {
            "StaminaModifier" : -1,
            "RegularDamage" : 3,
            "RegularDamageMax" : 4,
            "ArmorDamageMult" : 1.0,
            "DirectDamageMult" : 0.4,
        },
        "weapon.heavy_southern_mace" : {
            "StaminaModifier" : -1,
            "RegularDamage" : 3,
            "RegularDamageMax" : 5,
            "ArmorDamageMult" : 1.2,
            "DirectDamageMult" : 0.4,
        },
        "weapon.orc_metal_club" : {
            "StaminaModifier" : -1,
            "RegularDamage" : 3,
            "RegularDamageMax" : 5,
            "ArmorDamageMult" : 0.9,
            "DirectDamageMult" : 0.4,
        },
        "weapon.named_mace" : {
            "StaminaModifier" : -1,
            "RegularDamage" : 3,
            "RegularDamageMax" : 5,
            "ArmorDamageMult" : 1.1,
            "DirectDamageMult" : 0.4,
        },
        "weapon.winged_mace" : {
            "StaminaModifier" : -1,
            "RegularDamage" : 3,
            "RegularDamageMax" : 5,
            "ArmorDamageMult" : 1.1,
            "DirectDamageMult" : 0.4,
        },
        // 2H 
        "weapon.named_two_handed_spiked_mace" : {
            "StaminaModifier" : -2,
            "RegularDamage" : 5,
            "RegularDamageMax" : 7,
            "ArmorDamageMult" : 1.15,
            "DirectDamageMult" : 0.5,
            "ChanceToHitHead" : 0,
        },
        "weapon.two_handed_spiked_mace" : {
            "StaminaModifier" : -2,
            "RegularDamage" : 5,
            "RegularDamageMax" : 7,
            "ArmorDamageMult" : 1.15,
            "DirectDamageMult" : 0.5,
            "ChanceToHitHead" : 0,
        },
        "weapon.named_polemace" : {
            "StaminaModifier" : -2,
            "RangeMin" : 1,
            "RangeMax" : 2,
            "RangeIdeal" : 2,
            "RegularDamage" : 6,
            "RegularDamageMax" : 7,
            "ArmorDamageMult" : 1.2,
            "DirectDamageMult" : 0.4,
            "ChanceToHitHead" : 5,
        },
        "weapon.polemace" : {
            "StaminaModifier" : -2,
            "RangeMin" : 1,
            "RangeMax" : 2,
            "RangeIdeal" : 2,
            "RegularDamage" : 6,
            "RegularDamageMax" : 7,
            "ArmorDamageMult" : 1.2,
            "DirectDamageMult" : 0.4,
            "ChanceToHitHead" : 5,
        },
        "weapon.two_handed_mace" : {
            "StaminaModifier" : -2,
            "RegularDamage" : 5,
            "RegularDamageMax" : 7,
            "ArmorDamageMult" : 1.15,
            "DirectDamageMult" : 0.5,
            "ChanceToHitHead" : 0,
        },
        "weapon.named_two_handed_mace" : {
            "StaminaModifier" : -2,
            "RegularDamage" : 7,
            "RegularDamageMax" : 9,
            "ArmorDamageMult" : 1.25,
            "DirectDamageMult" : 0.5,
            "ChanceToHitHead" : 0,
        },
        "weapon.two_handed_flanged_mace" : {
            "StaminaModifier" : -2,
            "RegularDamage" : 7,
            "RegularDamageMax" : 9,
            "ArmorDamageMult" : 1.25,
            "DirectDamageMult" : 0.5,
            "ChanceToHitHead" : 0,
        },
    
    
    
    //==================================================================================================
    //Hammer 
    //==================================================================================================
    
        // 1H 
        "weapon.axehammer" : {
            "StaminaModifier" : -1,
            "RegularDamage" : 2,
            "RegularDamageMax" : 3,
            "ArmorDamageMult" : 2.0,
            "DirectDamageMult" : 0.5,
        },
        "weapon.pickaxe" : {
            "StaminaModifier" : -1,
            "RegularDamage" : 1,
            "RegularDamageMax" : 3,
            "ArmorDamageMult" : 1.5,
            "DirectDamageMult" : 0.5,
        },
        "weapon.military_pick" : {
            "StaminaModifier" : -1,
            "RegularDamage" : 2,
            "RegularDamageMax" : 3,
            "ArmorDamageMult" : 2.0,
            "DirectDamageMult" : 0.5,
        },
        "weapon.named_warhammer" : {
            "StaminaModifier" : -1,
            "RegularDamage" : 3,
            "RegularDamageMax" : 4,
            "ArmorDamageMult" : 2.25,
            "DirectDamageMult" : 0.5,
        },
        "weapon.warhammer" : {
            "StaminaModifier" : -1,
            "RegularDamage" : 3,
            "RegularDamageMax" : 4,
            "ArmorDamageMult" : 2.25,
            "DirectDamageMult" : 0.5,
        },
        // 2H 
        "weapon.named_skullhammer" : {
            "StaminaModifier" : -2,
            "RegularDamage" : 4,
            "RegularDamageMax" : 6,
            "ArmorDamageMult" : 1.8,
            "DirectDamageMult" : 0.5,
            "ChanceToHitHead" : 0,
        },
        "weapon.skull_hammer" : {
            "StaminaModifier" : -2,
            "RegularDamage" : 4,
            "RegularDamageMax" : 6,
            "ArmorDamageMult" : 1.8,
            "DirectDamageMult" : 0.5,
            "ChanceToHitHead" : 0,
        },
        "weapon.two_handed_wooden_hammer" : {
            "StaminaModifier" : -2,
            "RegularDamage" : 4,
            "RegularDamageMax" : 7,
            "ArmorDamageMult" : 1.5,
            "DirectDamageMult" : 0.5,
            "ChanceToHitHead" : 0,
        },
        "weapon.named_polehammer" : {
            "StaminaModifier" : -2,
            "RangeMin" : 1,
            "RangeMax" : 2,
            "RangeIdeal" : 2,
            "RegularDamage" : 5,
            "RegularDamageMax" : 7,
            "ArmorDamageMult" : 1.85,
            "DirectDamageMult" : 0.5,
            "ChanceToHitHead" : 5,
        },
        "weapon.polehammer" : {
            "StaminaModifier" : -2,
            "RangeMin" : 1,
            "RangeMax" : 2,
            "RangeIdeal" : 2,
            "RegularDamage" : 5,
            "RegularDamageMax" : 7,
            "ArmorDamageMult" : 1.85,
            "DirectDamageMult" : 0.5,
            "ChanceToHitHead" : 5,
        },
        "weapon.named_two_handed_hammer" : {
            "StaminaModifier" : -2,
            "RegularDamage" : 6,
            "RegularDamageMax" : 9,
            "ArmorDamageMult" : 2.0,
            "DirectDamageMult" : 0.5,
            "ChanceToHitHead" : 0,
        },
        "weapon.two_handed_hammer" : {
            "StaminaModifier" : -2,
            "RegularDamage" : 6,
            "RegularDamageMax" : 9,
            "ArmorDamageMult" : 2.0,
            "DirectDamageMult" : 0.5,
            "ChanceToHitHead" : 0,
        },
    
    
    
    //==================================================================================================
    //Flail 
    //==================================================================================================
    
        // 1H 
        "weapon.wooden_flail" : {
            "StaminaModifier" : -1,
            "RegularDamage" : 1,
            "RegularDamageMax" : 2,
            "ArmorDamageMult" : 0.5,
            "DirectDamageMult" : 0.3,
            "ChanceToHitHead" : 10,
        },
        "weapon.reinforced_wooden_flail" : {
            "StaminaModifier" : -1,
            "RegularDamage" : 2,
            "RegularDamageMax" : 4,
            "ArmorDamageMult" : 0.8,
            "ChanceToHitHead" : 10,
            "DirectDamageMult" : 0.3,
        },
        "weapon.flail" : {
            "StaminaModifier" : -1,
            "RegularDamage" : 2,
            "RegularDamageMax" : 5,
            "ArmorDamageMult" : 1.0,
            "DirectDamageMult" : 0.3,
            "ChanceToHitHead" : 10,
        },
        "weapon.named_flail" : {
            "StaminaModifier" : -1,
            "RegularDamage" : 2,
            "RegularDamageMax" : 5,
            "ArmorDamageMult" : 1.0,
            "DirectDamageMult" : 0.3,
            "ChanceToHitHead" : 10,
        },
        "weapon.named_three_headed_flail" : {
            "StaminaModifier" : -1,
            "RegularDamage" : 3,
            "RegularDamageMax" : 7,
            "ArmorDamageMult" : 1.0,
            "DirectDamageMult" : 0.3,
            "ChanceToHitHead" : 10,
        },
        "weapon.three_headed_flail" : {
            "StaminaModifier" : -1,
            "RegularDamage" : 3,
            "RegularDamageMax" : 7,
            "ArmorDamageMult" : 1.0,
            "DirectDamageMult" : 0.3,
            "ChanceToHitHead" : 10,
        },
        // 2H 
        "weapon.two_handed_wooden_flail" : {
            "StaminaModifier" : -2,
            "RegularDamage" : 3,
            "RegularDamageMax" : 6,
            "ArmorDamageMult" : 0.8,
            "DirectDamageMult" : 0.3,
            "ChanceToHitHead" : 15,
        },
        "weapon.named_two_handed_flail" : {
            "StaminaModifier" : -2,
            "RegularDamage" : 4,
            "RegularDamageMax" : 9,
            "ArmorDamageMult" : 1.15,
            "DirectDamageMult" : 0.3,
            "ChanceToHitHead" : 15,
        },
        "weapon.two_handed_flail" : {
            "StaminaModifier" : -2,
            "RegularDamage" : 4,
            "RegularDamageMax" : 9,
            "ArmorDamageMult" : 1.15,
            "DirectDamageMult" : 0.3,
            "ChanceToHitHead" : 15,
        },
        "weapon.orc_flail_2h" : {
            "StaminaModifier" : -2,
            "RegularDamage" : 5,
            "RegularDamageMax" : 10,
            "ArmorDamageMult" : 1.25,
            "DirectDamageMult" : 0.3,
            "ChanceToHitHead" : 15,
        },
        "weapon.miasma_flail" : {
            "StaminaModifier" : -2,
            "RangeMin" : 1,
            "RangeMax" : 2,
            "RangeIdeal" : 2,
            "RegularDamage" : 6,
            "RegularDamageMax" : 11,
            "ArmorDamageMult" : 1.1,
            "DirectDamageMult" : 0.3,
            "ChanceToHitHead" : 15,
        },
    
    
    
    //==================================================================================================
    //Bow 
    //==================================================================================================
    
        // 1H 
        // 2H 
        "weapon.goblin_bow" : {
            "StaminaModifier" : -2,
            "RangeMin" : 2,
            "RangeMax" : 6,
            "RangeIdeal" : 6,
            "RegularDamage" : 2,
            "RegularDamageMax" : 4,
            "ArmorDamageMult" : 0.55,
            "DirectDamageMult" : 0.35,
        },
        "weapon.goblin_heavy_bow" : {
            "StaminaModifier" : -2,
            "RangeMin" : 2,
            "RangeMax" : 7,
            "RangeIdeal" : 7,
            "RegularDamage" : 3,
            "RegularDamageMax" : 5,
            "ArmorDamageMult" : 0.6,
            "DirectDamageMult" : 0.35,
        },
        "weapon.named_goblin_heavy_bow" : {
            "StaminaModifier" : -2,
            "RangeMin" : 2,
            "RangeMax" : 7,
            "RangeIdeal" : 7,
            "RegularDamage" : 3,
            "RegularDamageMax" : 5,
            "ArmorDamageMult" : 0.6,
            "DirectDamageMult" : 0.35,
        },
        "weapon.short_bow" : {
            "StaminaModifier" : -2,
            "RangeMin" : 2,
            "RangeMax" : 7,
            "RangeIdeal" : 7,
            "RegularDamage" : 3,
            "RegularDamageMax" : 5,
            "ArmorDamageMult" : 0.5,
            "DirectDamageMult" : 0.35,
        },
        "weapon.wonky_bow" : {
            "RangeMin" : 2,
            "RangeMax" : 7,
            "RangeIdeal" : 7,
            "StaminaModifier" : -2,
            "RegularDamage" : 3,
            "RegularDamageMax" : 5,
            "ArmorDamageMult" : 0.5,
            "DirectDamageMult" : 0.35,
        },
        "weapon.composite_bow" : {
            "StaminaModifier" : -2,
            "RangeMin" : 2,
            "RangeMax" : 6,
            "RangeIdeal" : 6,
            "RegularDamage" : 4,
            "RegularDamageMax" : 5,
            "ArmorDamageMult" : 0.7,
            "DirectDamageMult" : 0.35,
        },
        "weapon.hunting_bow" : {
            "RangeMin" : 2,
            "RangeMax" : 7,
            "RangeIdeal" : 7,
            "StaminaModifier" : -2,
            "RegularDamage" : 4,
            "RegularDamageMax" : 6,
            "ArmorDamageMult" : 0.55,
            "DirectDamageMult" : 0.35,
        },
        "weapon.named_warbow" : {
            "RangeMin" : 2,
            "RangeMax" : 7,
            "RangeIdeal" : 7,
            "StaminaModifier" : -2,
            "RegularDamage" : 5,
            "RegularDamageMax" : 7,
            "ArmorDamageMult" : 0.6,
            "DirectDamageMult" : 0.35,
        },
        "weapon.war_bow" : {
            "RangeMin" : 2,
            "RangeMax" : 7,
            "RangeIdeal" : 7,
            "StaminaModifier" : -2,
            "RegularDamage" : 5,
            "RegularDamageMax" : 7,
            "ArmorDamageMult" : 0.6,
            "DirectDamageMult" : 0.35,
        },
        "weapon.masterwork_bow" : {
            "RangeMin" : 2,
            "RangeMax" : 7,
            "RangeIdeal" : 7,
            "StaminaModifier" : -2,
            "RegularDamage" : 5,
            "RegularDamageMax" : 7,
            "ArmorDamageMult" : 0.65,
            "DirectDamageMult" : 0.35,
        },
    
    
    
    //==================================================================================================
    //Crossbow 
    //==================================================================================================
    
        // 1H 
        // 2H 
        "weapon.light_crossbow" : {
            "RangeMin" : 1,
            "RangeMax" : 6,
            "RangeIdeal" : 6,
            "StaminaModifier" : -2,
            "RegularDamage" : 3,
            "RegularDamageMax" : 5,
            "ArmorDamageMult" : 0.6,
            "DirectDamageMult" : 0.5,
        },
        "weapon.crossbow" : {
            "RangeMin" : 1,
            "RangeMax" : 6,
            "RangeIdeal" : 6,
            "StaminaModifier" : -2,
            "RegularDamage" : 4,
            "RegularDamageMax" : 6,
            "ArmorDamageMult" : 0.7,
            "DirectDamageMult" : 0.5,
        },
        "weapon.goblin_crossbow" : {
            "RangeMin" : 1,
            "RangeMax" : 6,
            "RangeIdeal" : 6,
            "StaminaModifier" : -2,
            "RegularDamage" : 5,
            "RegularDamageMax" : 7,
            "ArmorDamageMult" : 0.75,
            "DirectDamageMult" : 0.5,
        },
        "weapon.heavy_crossbow" : {
            "RangeMin" : 1,
            "RangeMax" : 6,
            "RangeIdeal" : 6,
            "StaminaModifier" : -2,
            "RegularDamage" : 5,
            "RegularDamageMax" : 7,
            "ArmorDamageMult" : 0.75,
            "DirectDamageMult" : 0.5,
        },
        "weapon.named_crossbow" : {
            "RangeMin" : 1,
            "RangeMax" : 6,
            "RangeIdeal" : 6,
            "StaminaModifier" : -2,
            "RegularDamage" : 5,
            "RegularDamageMax" : 7,
            "ArmorDamageMult" : 0.75,
            "DirectDamageMult" : 0.5,
        },
        "weapon.named_goblin_crossbow" : {
            "RangeMin" : 1,
            "RangeMax" : 6,
            "RangeIdeal" : 6,
            "StaminaModifier" : -2,
            "RegularDamage" : 5,
            "RegularDamageMax" : 7,
            "ArmorDamageMult" : 0.75,
            "DirectDamageMult" : 0.5,
        },
    
    
    
    //==================================================================================================
    //ThrowingWeapon 
    //==================================================================================================
    
        // 1H 
        "weapon.goblin_spiked_balls" : {
            "RangeMin" : 2,
            "RangeMax" : 4,
            "RangeIdeal" : 4,
            "StaminaModifier" : -1,
            "RegularDamage" : 2,
            "RegularDamageMax" : 3,
            "ArmorDamageMult" : 0.7,
            "DirectDamageMult" : 0.4,
        },
        "weapon.named_throwing_axe" : {
            "RangeMin" : 2,
            "RangeMax" : 4,
            "RangeIdeal" : 4,
            "StaminaModifier" : -1,
            "RegularDamage" : 2,
            "RegularDamageMax" : 4,
            "ArmorDamageMult" : 1.1,
            "DirectDamageMult" : 0.3,
            "ChanceToHitHead" : 5,
        },
        "weapon.orc_javelin" : {
            "RangeMin" : 1,
            "RangeMax" : 4,
            "RangeIdeal" : 4,
            "StaminaModifier" : -1,
            "RegularDamage" : 3,
            "RegularDamageMax" : 4,
            "ArmorDamageMult" : 0.7,
            "DirectDamageMult" : 0.45,
        },
        "weapon.throwing_axe" : {
            "RangeMin" : 2,
            "RangeMax" : 4,
            "RangeIdeal" : 4,
            "StaminaModifier" : -1,
            "RegularDamage" : 2,
            "RegularDamageMax" : 4,
            "ArmorDamageMult" : 1.1,
            "DirectDamageMult" : 0.3,
            "ChanceToHitHead" : 5,
        },
        "weapon.javelin" : {
            "RangeMin" : 1,
            "RangeMax" : 4,
            "RangeIdeal" : 4,
            "StaminaModifier" : -1,
            "RegularDamage" : 3,
            "RegularDamageMax" : 4,
            "ArmorDamageMult" : 0.75,
            "DirectDamageMult" : 0.45,
        },
        "weapon.named_javelin" : {
            "RangeMin" : 1,
            "RangeMax" : 4,
            "RangeIdeal" : 4,
            "StaminaModifier" : -1,
            "RegularDamage" : 3,
            "RegularDamageMax" : 4,
            "ArmorDamageMult" : 0.75,
            "DirectDamageMult" : 0.45,
        },
        "weapon.heavy_javelin" : {
            "RangeMin" : 1,
            "RangeMax" : 4,
            "RangeIdeal" : 4,
            "StaminaModifier" : -1,
            "RegularDamage" : 3,
            "RegularDamageMax" : 5,
            "ArmorDamageMult" : 0.8,
            "DirectDamageMult" : 0.45,
        },
        "weapon.heavy_throwing_axe" : {
            "RangeMin" : 2,
            "RangeMax" : 4,
            "RangeIdeal" : 4,
            "StaminaModifier" : -1,
            "RegularDamage" : 3,
            "RegularDamageMax" : 5,
            "ArmorDamageMult" : 1.15,
            "DirectDamageMult" : 0.3,
            "ChanceToHitHead" : 5,
        },
        "weapon.legend_orc_throwing_spear" : {
            "RangeMin" : 1,
            "RangeMax" : 4,
            "RangeIdeal" : 4,
            "StaminaModifier" : -1,
            "RegularDamage" : 3,
            "RegularDamageMax" : 6,
            "ArmorDamageMult" : 1.3,
            "DirectDamageMult" : 0.4,
        },
        "weapon.throwing_spear" : {
            "RangeMin" : 2,
            "RangeMax" : 4,
            "RangeIdeal" : 4,
            "StaminaModifier" : -1,
            "RegularDamage" : 4,
            "RegularDamageMax" : 7,
            "ArmorDamageMult" : 1.1,
            "DirectDamageMult" : 0.45,
        },
        // 2H 
        "weapon.staff_sling" : {
            "StaminaModifier" : -2,
            "RangeMin" : 2,
            "RangeMax" : 6,
            "RangeIdeal" : 6,
            "RegularDamage" : 2,
            "RegularDamageMax" : 4,
            "ArmorDamageMult" : 0.5,
            "DirectDamageMult" : 0.35,
        },
        "weapon.nomad_sling" : {
            "StaminaModifier" : -2,
            "RangeMin" : 2,
            "RangeMax" : 6,
            "RangeIdeal" : 6,
            "RegularDamage" : 3,
            "RegularDamageMax" : 5,
            "ArmorDamageMult" : 0.6,
            "DirectDamageMult" : 0.35,
        },
    
    
    
    //==================================================================================================
    //MusicalInstrument 
    //==================================================================================================
    
        // 1H 
        // 2H 
        "weapon.lute" : {
            "StaminaModifier" : -2,
            "RegularDamage" : 0,
            "RegularDamageMax" : 1,
            "ArmorDamageMult" : 0.1,
            "DirectDamageMult" : 0.4,
        },
    
    
    
    //==================================================================================================
    //Firearm 
    //==================================================================================================
    
        // 1H 
        // 2H 
        "weapon.handgonne" : {
            "RangeMin" : 2,
            "RangeMax" : 2,
            "RangeIdeal" : 2,
            "StaminaModifier" : -2,
            "RegularDamage" : 3,
            "RegularDamageMax" : 7,
            "ArmorDamageMult" : 0.9,
            "DirectDamageMult" : 0.25,
        },
        "weapon.named_handgonne" : {
            "RangeMin" : 2,
            "RangeMax" : 2,
            "RangeIdeal" : 2,
            "StaminaModifier" : -2,
            "RegularDamage" : 3,
            "RegularDamageMax" : 7,
            "ArmorDamageMult" : 0.9,
            "DirectDamageMult" : 0.25,
        },
    
    
    
    //==================================================================================================
    //Bad Sorting, Dev Didn't Categorize In Code Correctly 
    //==================================================================================================
    
        // 1H 
        "weapon.golem_cleaver_hammer" : {
            "RangeMin" : 1,
            "RangeMax" : 1,
            "RangeIdeal" : 1,
            "StaminaModifier" : -1,
            "RegularDamage" : 0,
            "RegularDamageMax" : 0,
            "ArmorDamageMult" : 0.0,
            "DirectDamageMult" : 0.0,
        },
        "weapon.golem_mace_flail" : {
            "RangeMin" : 1,
            "RangeMax" : 1,
            "RangeIdeal" : 1,
            "StaminaModifier" : -1,
            "RegularDamage" : 0,
            "RegularDamageMax" : 0,
            "ArmorDamageMult" : 0.0,
            "DirectDamageMult" : 0.0,
        },
        "weapon.golem_mace_hammer" : {
            "RangeMin" : 1,
            "RangeMax" : 1,
            "RangeIdeal" : 1,
            "StaminaModifier" : -1,
            "RegularDamage" : 0,
            "RegularDamageMax" : 0,
            "ArmorDamageMult" : 0.0,
            "DirectDamageMult" : 0.0,
        },
        "weapon.golem_spear_sword" : {
            "RangeMin" : 1,
            "RangeMax" : 1,
            "RangeIdeal" : 1,
            "StaminaModifier" : -1,
            "RegularDamage" : 0,
            "RegularDamageMax" : 0,
            "ArmorDamageMult" : 0.0,
            "DirectDamageMult" : 0.0,
        },
        "weapon.barbarian_drum" : {
            "RangeMin" : 1,
            "RangeMax" : 6,
            "RangeIdeal" : 6,
            "StaminaModifier" : -1,
            "RegularDamage" : 0,
            "RegularDamageMax" : 0,
            "ArmorDamageMult" : 0.0,
            "DirectDamageMult" : 0.0,
        },
        "weapon.legend_drum" : {
            "StaminaModifier" : -1,
            "RegularDamage" : 0,
            "RegularDamageMax" : 1,
            "ArmorDamageMult" : 0.5,
            "DirectDamageMult" : 0.4,
        },
        "weapon.legend_blowgun" : {
            "RangeMin" : 1,
            "RangeMax" : 5,
            "RangeIdeal" : 4,
            "StaminaModifier" : -1,
            "RegularDamage" : 0,
            "RegularDamageMax" : 1,
            "ArmorDamageMult" : 0.2,
            "DirectDamageMult" : 0.1,
        },
        "weapon.legend_cat_o_nine_tails" : {
            "RangeMin" : 1,
            "RangeMax" : 1,
            "RangeIdeal" : 1,
            "StaminaModifier" : -1,
            "RegularDamage" : 1,
            "RegularDamageMax" : 1,
            "ArmorDamageMult" : 0.15,
            "DirectDamageMult" : 0.1,
        },
        "weapon.legend_wooden_stake" : {
            "RegularDamage" : 1,
            "RegularDamageMax" : 1,
            "ArmorDamageMult" : 0.1,
            "DirectDamageMult" : 0.3,
        },
        "weapon.legend_hammer" : {
            "StaminaModifier" : -1,
            "RegularDamage" : 1,
            "RegularDamageMax" : 2,
            "ArmorDamageMult" : 1.5,
            "DirectDamageMult" : 0.5,
        },
        "weapon.legend_hoe" : {
            "StaminaModifier" : -1,
            "RegularDamage" : 1,
            "RegularDamageMax" : 2,
            "ArmorDamageMult" : 0.6,
            "DirectDamageMult" : 0.3,
        },
        "weapon.legend_saw" : {
            "StaminaModifier" : -1,
            "RegularDamage" : 1,
            "RegularDamageMax" : 2,
            "ArmorDamageMult" : 0.4,
            "DirectDamageMult" : 0.25,
        },
        "weapon.legend_shiv" : {
            "RegularDamage" : 1,
            "RegularDamageMax" : 2,
            "ArmorDamageMult" : 0.3,
            "DirectDamageMult" : 0.2,
        },
        "weapon.sickle" : {
            "StaminaModifier" : -1,
            "RegularDamage" : 1,
            "RegularDamageMax" : 2,
            "ArmorDamageMult" : 0.5,
            "DirectDamageMult" : -0.05,
        },
        "weapon.legend_named_lute" : {
            "StaminaModifier" : -1,
            "RegularDamage" : 1,
            "RegularDamageMax" : 2,
            "ArmorDamageMult" : 1.1,
            "DirectDamageMult" : 0.4,
        },
        "weapon.legend_slingshot" : {
            "StaminaModifier" : -1,
            "RangeMin" : 2,
            "RangeMax" : 4,
            "RangeIdeal" : 4,
            "RegularDamage" : 1,
            "RegularDamageMax" : 2,
            "ArmorDamageMult" : 0.1,
            "DirectDamageMult" : 0.4,
        },
        "weapon.legend_wooden_spear" : {
            "StaminaModifier" : -1,
            "RegularDamage" : 1,
            "RegularDamageMax" : 2,
            "ArmorDamageMult" : 0.45,
            "DirectDamageMult" : 0.25,
        },
        "weapon.legend_named_blacksmith_hammer" : {
            "StaminaModifier" : -1,
            "RegularDamage" : 2,
            "RegularDamageMax" : 3,
            "ArmorDamageMult" : 2.0,
            "DirectDamageMult" : 0.5,
        },
        "weapon.legend_scythe" : {
            "StaminaModifier" : -1,
            "RangeMin" : 1,
            "RangeMax" : 2,
            "RangeIdeal" : 2,
            "RegularDamage" : 1,
            "RegularDamageMax" : 3,
            "ArmorDamageMult" : 0.25,
            "DirectDamageMult" : 0.25,
        },
        "weapon.legend_shovel" : {
            "StaminaModifier" : -1,
            "RegularDamage" : 2,
            "RegularDamageMax" : 3,
            "ArmorDamageMult" : 0.45,
            "DirectDamageMult" : 0.4,
            "ChanceToHitHead" : 5,
        },
        "weapon.legend_sling" : {
            "StaminaModifier" : -1,
            "RangeMin" : 2,
            "RangeMax" : 6,
            "RangeIdeal" : 6,
            "ArmorDamageMult" : 0.75,
            "DirectDamageMult" : 0.4,
            "RegularDamage" : 2,
            "RegularDamageMax" : 3,
        },
        "weapon.legend_staff" : {
            "StaminaModifier" : -1,
            "RangeMin" : 1,
            "RangeMax" : 2,
            "RangeIdeal" : 2,
            "RegularDamage" : 2,
            "RegularDamageMax" : 3,
            "ArmorDamageMult" : 0.3,
            "DirectDamageMult" : 0.4,
        },
        "weapon.legend_staff_vala" : {
            "StaminaModifier" : -1,
            "RangeMin" : 1,
            "RangeMax" : 2,
            "RangeIdeal" : 2,
            "RegularDamage" : 2,
            "RegularDamageMax" : 3,
            "ArmorDamageMult" : 0.6,
            "DirectDamageMult" : 0.4,
        },
        "weapon.legend_grisly_scythe" : {
            "StaminaModifier" : -1,
            "RegularDamage" : 2,
            "RegularDamageMax" : 3,
            "ArmorDamageMult" : 0.5,
            "DirectDamageMult" : 0.25,
        },
        "weapon.legend_wooden_pitchfork" : {
            "StaminaModifier" : -1,
            "RangeMin" : 1,
            "RangeMax" : 2,
            "RangeIdeal" : 2,
            "RegularDamage" : 1,
            "RegularDamageMax" : 3,
            "ArmorDamageMult" : 0.2,
            "DirectDamageMult" : 0.3,
        },
        "weapon.legend_hand_crossbow" : {
            "RangeMin" : 1,
            "RangeMax" : 5,
            "RangeIdeal" : 4,
            "StaminaModifier" : -1,
            "RegularDamage" : 2,
            "RegularDamageMax" : 4,
            "ArmorDamageMult" : 0.4,
            "DirectDamageMult" : 0.5,
        },
        "weapon.legend_named_nomad_sling" : {
            "RangeMin" : 2,
            "RangeMax" : 8,
            "RangeIdeal" : 8,
            "RegularDamage" : 3,
            "RegularDamageMax" : 4,
            "ArmorDamageMult" : 1.0,
            "DirectDamageMult" : 0.7,
            "StaminaModifier" : -1,
        },
        "weapon.legend_tipstaff" : {
            "StaminaModifier" : -1,
            "RangeMin" : 1,
            "RangeMax" : 2,
            "RangeIdeal" : 2,
            "RegularDamage" : 3,
            "RegularDamageMax" : 4,
            "ArmorDamageMult" : 0.3,
            "DirectDamageMult" : 0.4,
        },
        "weapon.legend_chain" : {
            "StaminaModifier" : -1,
            "RangeMin" : 1,
            "RangeMax" : 3,
            "RangeIdeal" : 1,
            "RegularDamage" : 1,
            "RegularDamageMax" : 4,
            "ArmorDamageMult" : 0.3,
            "DirectDamageMult" : 0.2,
            "ChanceToHitHead" : 10,
        },
        "weapon.legend_katar" : {
            "RegularDamage" : 3,
            "RegularDamageMax" : 4,
            "ArmorDamageMult" : 1.25,
            "DirectDamageMult" : 0.3,
        },
        "weapon.legend_kopis" : {
            "StaminaModifier" : -1,
            "RegularDamage" : 3,
            "RegularDamageMax" : 4,
            "ArmorDamageMult" : 1.0,
            "DirectDamageMult" : 0.25,
        },
        "weapon.legend_named_northern_sling" : {
            "RangeMin" : 2,
            "RangeMax" : 9,
            "RangeIdeal" : 9,
            "StaminaModifier" : -1,
            "RegularDamage" : 3,
            "RegularDamageMax" : 4,
            "ArmorDamageMult" : 1.1,
            "DirectDamageMult" : 0.75,
        },
        "weapon.legend_named_warhammer" : {
            "StaminaModifier" : -1,
            "RegularDamage" : 3,
            "RegularDamageMax" : 4,
            "ArmorDamageMult" : 2.5,
            "DirectDamageMult" : 0.5,
        },
        "weapon.legend_northern_sling" : {
            "RangeMin" : 2,
            "RangeMax" : 9,
            "RangeIdeal" : 9,
            "StaminaModifier" : -1,
            "RegularDamage" : 3,
            "RegularDamageMax" : 4,
            "ArmorDamageMult" : 1.1,
            "DirectDamageMult" : 0.75,
        },
        "weapon.legend_gladius" : {
            "StaminaModifier" : -1,
            "RegularDamage" : 4,
            "RegularDamageMax" : 4,
            "ArmorDamageMult" : 0.8,
            "DirectDamageMult" : 0.2,
        },
        "weapon.legend_named_gladius" : {
            "StaminaModifier" : -1,
            "RegularDamage" : 4,
            "RegularDamageMax" : 4,
            "ArmorDamageMult" : 0.8,
            "DirectDamageMult" : 0.2,
        },
        "weapon.legend_mystic_staff" : {
            "StaminaModifier" : -1,
            "RangeMin" : 1,
            "RangeMax" : 2,
            "RangeIdeal" : 2,
            "RegularDamage" : 4,
            "RegularDamageMax" : 5,
            "ArmorDamageMult" : 0.3,
            "DirectDamageMult" : 0.4,
        },
        "weapon.legend_named_butchers_cleaver" : {
            "StaminaModifier" : -1,
            "RegularDamage" : 3,
            "RegularDamageMax" : 5,
            "ArmorDamageMult" : 0.75,
            "DirectDamageMult" : 0.25,
        },
        "weapon.legend_named_heavy_southern_mace" : {
            "StaminaModifier" : -1,
            "RegularDamage" : 3,
            "RegularDamageMax" : 5,
            "ArmorDamageMult" : 1.2,
            "DirectDamageMult" : 0.4,
        },
        "weapon.legend_ranged_wooden_flail" : {
            "StaminaModifier" : -1,
            "RangeMin" : 1,
            "RangeMax" : 2,
            "RangeIdeal" : 2,
            "RegularDamage" : 2,
            "RegularDamageMax" : 5,
            "ArmorDamageMult" : 0.5,
            "DirectDamageMult" : 0.3,
            "ChanceToHitHead" : 10,
        },
        "weapon.legend_skullsmasher" : {
            "StaminaModifier" : -1,
            "RegularDamage" : 3,
            "RegularDamageMax" : 5,
            "ArmorDamageMult" : 2.25,
            "DirectDamageMult" : 0.5,
            "ChanceToHitHead" : 0,
        },
        "weapon.legend_redback_dagger" : {
            "RegularDamage" : 2,
            "RegularDamageMax" : 5,
            "ArmorDamageMult" : 0.7,
            "DirectDamageMult" : 0.36,
        },
        "weapon.legend_brass_khopesh" : {
            "StaminaModifier" : -1,
            "RegularDamage" : 4,
            "RegularDamageMax" : 5,
            "ArmorDamageMult" : 1.10,
            "DirectDamageMult" : 0.25,
        },
        "weapon.legend_militia_glaive" : {
            "StaminaModifier" : -1,
            "RangeMin" : 1,
            "RangeMax" : 2,
            "RangeIdeal" : 2,
            "RegularDamage" : 4,
            "RegularDamageMax" : 5,
            "ArmorDamageMult" : 0.9,
            "DirectDamageMult" : 0.25,
        },
        "weapon.legend_named_shovel" : {
            "StaminaModifier" : -1,
            "RegularDamage" : 4,
            "RegularDamageMax" : 5,
            "ArmorDamageMult" : 0.80,
            "DirectDamageMult" : 0.2,
            "ChanceToHitHead" : 10,
        },
        "weapon.legend_named_sickle" : {
            "StaminaModifier" : -1,
            "RegularDamage" : 4,
            "RegularDamageMax" : 5,
            "ArmorDamageMult" : 0.9,
            "DirectDamageMult" : 0.2,
            "ChanceToHitHead" : 5,
        },
        "weapon.legend_bone_carver" : {
            "StaminaModifier" : -1,
            "RegularDamage" : 3,
            "RegularDamageMax" : 6,
            "ArmorDamageMult" : 1.0,
            "DirectDamageMult" : 0.25,
        },
        "weapon.legend_estoc" : {
            "StaminaModifier" : -1,
            "RegularDamage" : 4,
            "RegularDamageMax" : 6,
            "ArmorDamageMult" : 0.60,
            "DirectDamageMult" : 0.2,
            "ChanceToHitHead" : 5,
        },
        "weapon.legend_named_estoc" : {
            "StaminaModifier" : -1,
            "RegularDamage" : 4,
            "RegularDamageMax" : 6,
            "ArmorDamageMult" : 0.60,
            "DirectDamageMult" : 0.2,
            "ChanceToHitHead" : 5,
        },
        "weapon.legend_skin_flayer" : {
            "StaminaModifier" : -1,
            "RegularDamage" : 4,
            "RegularDamageMax" : 6,
            "ArmorDamageMult" : 0.9,
            "DirectDamageMult" : 0.2,
        },
        "weapon.legend_two_handed_club" : {
            "StaminaModifier" : -1,
            "RegularDamage" : 3,
            "RegularDamageMax" : 6,
            "ArmorDamageMult" : 1.0,
            "DirectDamageMult" : 0.5,
            "ChanceToHitHead" : 0,
        },
        "weapon.legend_meat_hacker" : {
            "StaminaModifier" : -1,
            "RegularDamage" : 4,
            "RegularDamageMax" : 6,
            "ArmorDamageMult" : 1.5,
            "DirectDamageMult" : 0.3,
            "ChanceToHitHead" : 0,
        },
        "weapon.legend_infantry_axe" : {
            "StaminaModifier" : -1,
            "RegularDamage" : 5,
            "RegularDamageMax" : 7,
            "ArmorDamageMult" : 1.25,
            "DirectDamageMult" : 0.35,
            "ChanceToHitHead" : 0,
        },
        "weapon.legend_named_infantry_axe" : {
            "StaminaModifier" : -1,
            "RegularDamage" : 5,
            "RegularDamageMax" : 7,
            "ArmorDamageMult" : 1.25,
            "DirectDamageMult" : 0.35,
            "ChanceToHitHead" : 0,
        },
        "weapon.legend_named_swordstaff" : {
            "StaminaModifier" : -1,
            "RegularDamage" : 5,
            "RegularDamageMax" : 7,
            "ArmorDamageMult" : 1.0,
            "DirectDamageMult" : 0.25,
            "ChanceToHitHead" : 5,
        },
        "weapon.legend_pole_flail" : {
            "StaminaModifier" : -1,
            "RangeMin" : 1,
            "RangeMax" : 2,
            "RangeIdeal" : 2,
            "RegularDamage" : 4,
            "RegularDamageMax" : 7,
            "ArmorDamageMult" : 1.0,
            "DirectDamageMult" : 0.3,
            "ChanceToHitHead" : 10,
        },
        "weapon.legend_reinforced_flail" : {
            "StaminaModifier" : -1,
            "RegularDamage" : 3,
            "RegularDamageMax" : 7,
            "ArmorDamageMult" : 0.95,
            "DirectDamageMult" : 0.3,
            "ChanceToHitHead" : 15,
        },
        "weapon.legend_swordstaff" : {
            "StaminaModifier" : -1,
            "RangeMin" : 1,
            "RangeMax" : 2,
            "RangeIdeal" : 2,
            "RegularDamage" : 5,
            "RegularDamageMax" : 7,
            "ArmorDamageMult" : 1.0,
            "DirectDamageMult" : 0.25,
            "ChanceToHitHead" : 5,
        },
        "weapon.legend_battle_glaive" : {
            "StaminaModifier" : -1,
            "RangeMin" : 1,
            "RangeMax" : 2,
            "RangeIdeal" : 2,
            "RegularDamage" : 6,
            "RegularDamageMax" : 7,
            "ArmorDamageMult" : 0.9,
            "DirectDamageMult" : 0.3,
        },
        "weapon.legend_crusader_sword" : {
            "StaminaModifier" : -1,
            "RegularDamage" : 6,
            "RegularDamageMax" : 7,
            "ArmorDamageMult" : 0.80,
            "DirectDamageMult" : 0.25,
            "ChanceToHitHead" : 10,
        },
        "weapon.legend_longsword" : {
            "StaminaModifier" : -1,
            "RegularDamage" : 5,
            "RegularDamageMax" : 7,
            "ArmorDamageMult" : 0.8,
            "DirectDamageMult" : 0.25,
            "ChanceToHitHead" : 10,
        },
        "weapon.legend_named_longsword_02" : {
            "StaminaModifier" : -1,
            "RegularDamage" : 5,
            "RegularDamageMax" : 7,
            "ArmorDamageMult" : 0.8,
            "DirectDamageMult" : 0.25,
            "ChanceToHitHead" : 10,
        },
        "weapon.legend_halberd" : {
            "StaminaModifier" : -1,
            "RangeMin" : 1,
            "RangeMax" : 2,
            "RangeIdeal" : 2,
            "RegularDamage" : 6,
            "RegularDamageMax" : 8,
            "ArmorDamageMult" : 1.5,
            "DirectDamageMult" : 0.3,
            "ChanceToHitHead" : 5,
        },
        "weapon.legend_named_flail" : {
            "StaminaModifier" : -1,
            "RangeMin" : 1,
            "RangeMax" : 2,
            "RangeIdeal" : 2,
            "RegularDamage" : 5,
            "RegularDamageMax" : 8,
            "ArmorDamageMult" : 1.0,
            "ChanceToHitHead" : 10,
            "DirectDamageMult" : 0.3,
        },
        "weapon.legend_named_glaive" : {
            "StaminaModifier" : -1,
            "RangeMin" : 1,
            "RangeMax" : 2,
            "RangeIdeal" : 2,
            "RegularDamage" : 6,
            "RegularDamageMax" : 8,
            "ArmorDamageMult" : 0.9,
            "DirectDamageMult" : 0.3,
        },
        "weapon.legend_named_halberd" : {
            "StaminaModifier" : -1,
            "RangeMin" : 1,
            "RangeMax" : 2,
            "RangeIdeal" : 2,
            "RegularDamage" : 6,
            "RegularDamageMax" : 8,
            "ArmorDamageMult" : 1.5,
            "DirectDamageMult" : 0.3,
            "ChanceToHitHead" : 5,
        },
        "weapon.legend_staff_gnarled" : {
            "StaminaModifier" : -1,
            "RangeMin" : 1,
            "RangeMax" : 2,
            "RangeIdeal" : 2,
            "RegularDamage" : 6,
            "RegularDamageMax" : 8,
            "ArmorDamageMult" : 0.3,
            "DirectDamageMult" : 0.4,
        },
        "weapon.legend_named_longsword" : {
            "StaminaModifier" : -1,
            "RegularDamage" : 6,
            "RegularDamageMax" : 8,
            "ArmorDamageMult" : 1.0,
            "DirectDamageMult" : 0.25,
            "ChanceToHitHead" : 10,
        },
        "weapon.legend_named_royal_lance" : {
            "StaminaModifier" : -1,
            "RegularDamage" : 6,
            "RegularDamageMax" : 8,
            "ArmorDamageMult" : 1.0,
            "DirectDamageMult" : 0.35,
            "ChanceToHitHead" : 5,
        },
        "weapon.legend_limb_lopper" : {
            "StaminaModifier" : -1,
            "RegularDamage" : 7,
            "RegularDamageMax" : 9,
            "ArmorDamageMult" : 1.3,
            "DirectDamageMult" : 0.25,
        },
        "weapon.legend_mage_swordstaff" : {
            "StaminaModifier" : -1,
            "RegularDamage" : 7,
            "RegularDamageMax" : 9,
            "ArmorDamageMult" : 1.0,
            "DirectDamageMult" : 0.25,
            "ChanceToHitHead" : 10,
        },
        "weapon.legend_fan_axe" : {
            "StaminaModifier" : -1,
            "RangeMin" : 1,
            "RangeMax" : 2,
            "RangeIdeal" : 2,
            "RegularDamage" : 6,
            "RegularDamageMax" : 9,
            "ArmorDamageMult" : 1.1,
            "DirectDamageMult" : 0.4,
            "ChanceToHitHead" : 10,
        },
        "weapon.legend_great_khopesh" : {
            "StaminaModifier" : -1,
            "RegularDamage" : 7,
            "RegularDamageMax" : 9,
            "ArmorDamageMult" : 1.2,
            "DirectDamageMult" : 0.25,
        },
        "weapon.legend_man_mangler" : {
            "StaminaModifier" : -1,
            "RegularDamage" : 6,
            "RegularDamageMax" : 9,
            "ArmorDamageMult" : 1.0,
            "DirectDamageMult" : 0.35,
            "ChanceToHitHead" : 5,
        },
        "weapon.legend_named_great_khopesh" : {
            "StaminaModifier" : -1,
            "RegularDamage" : 7,
            "RegularDamageMax" : 9,
            "ArmorDamageMult" : 1.2,
            "DirectDamageMult" : 0.25,
        },
        "weapon.legend_military_goedendag" : {
            "StaminaModifier" : -1,
            "RegularDamage" : 7,
            "RegularDamageMax" : 10,
            "ArmorDamageMult" : 1.25,
            "DirectDamageMult" : 0.4,
            "ChanceToHitHead" : 0,
        },
        "weapon.legend_named_orc_flail_2h" : {
            "StaminaModifier" : -1,
            "RegularDamage" : 5,
            "RegularDamageMax" : 10,
            "ArmorDamageMult" : 1.25,
            "DirectDamageMult" : 0.3,
            "ChanceToHitHead" : 15,
        },
        "weapon.legend_skullbreaker" : {
            "StaminaModifier" : -1,
            "RegularDamage" : 7,
            "RegularDamageMax" : 10,
            "ArmorDamageMult" : 2.1,
            "DirectDamageMult" : 0.5,
            "ChanceToHitHead" : 0,
        },
        "weapon.legend_bough" : {
            "StaminaModifier" : -1,
            "RegularDamage" : 8,
            "RegularDamageMax" : 11,
            "ArmorDamageMult" : 1.35,
            "DirectDamageMult" : 0.5,
            "ChanceToHitHead" : 0,
        },
        "weapon.legend_named_military_goedendag" : {
            "StaminaModifier" : -1,
            "RegularDamage" : 8,
            "RegularDamageMax" : 11,
            "ArmorDamageMult" : 1.25,
            "DirectDamageMult" : 0.4,
            "ChanceToHitHead" : 0,
        },
        "weapon.legend_named_orc_axe_2h" : {
            "StaminaModifier" : -1,
            "RegularDamage" : 9,
            "RegularDamageMax" : 12,
            "ArmorDamageMult" : 1.6,
            "DirectDamageMult" : 0.4,
            "ChanceToHitHead" : 0,
        },
        // 2H 
    
    
    
    };